// Shared schedule editor: preserve Chinese defaults and honor the existing language setting.
const english: Record<string, string> = {
  定时运行: 'Scheduled run',
  删除定时: 'Remove schedule',
  取消: 'Cancel',
  保存并应用: 'Save and apply',
  '加载定时配置...': 'Loading schedule…',
  '工作流正在运行，当前只能查看定时设置。':
    'This workflow is running. Schedule settings are read-only.',
  触发规则: 'Trigger rule',
  频率: 'Frequency',
  每隔几分钟: 'Every few minutes',
  每小时: 'Hourly',
  每天: 'Daily',
  工作日: 'Weekdays',
  每周: 'Weekly',
  每月: 'Monthly',
  '高级 Cron': 'Custom Cron',
  '间隔（分钟）': 'Interval (minutes)',
  '请输入 1–1440 的整数分钟数': 'Enter a whole number from 1 to 1440 minutes',
  分钟: 'Minute',
  时间: 'Time',
  星期: 'Weekday',
  星期一: 'Monday',
  星期二: 'Tuesday',
  星期三: 'Wednesday',
  星期四: 'Thursday',
  星期五: 'Friday',
  星期六: 'Saturday',
  星期日: 'Sunday',
  日期: 'Day of month',
  'Cron（分 时 日 月 周）': 'Cron (minute hour day month weekday)',
  时区: 'Timezone',
  标签: 'Label',
  可选: 'Optional',
  启用定时任务: 'Enable schedule',
  接下来: 'Next occurrences',
  运行输入: 'Runtime inputs',
  固定此值: 'Use a fixed value',
  必填: 'Required',
  敏感: 'Sensitive',
  触发时使用工作流当前默认值: 'Use the current workflow default at trigger time',
  '已保存敏感值，留空保持': 'Saved secret; leave blank to keep',
  '已保存敏感值，保存时保持不变': 'Saved secret will be preserved',
  必填输入必须固定一个值: 'Required input needs a fixed value',
  请输入有效数字: 'Enter a valid number',
  'JSON 格式无效': 'Invalid JSON',
  '读取定时配置失败：后端无响应': 'Could not load schedule: backend did not respond',
  '预览失败：后端无响应': 'Could not preview: backend did not respond',
}
export const scheduleText = (text: string, lang: string) =>
  lang === 'en' ? (english[text] ?? text) : text
