//! 随包只读 plugin 资产的编译期内嵌。
//!
//! 背景（issue #8 的遗留缺口）：`plugin/` 里混着两类东西——
//!   - **随包只读资产**：内置技能、ui-maps、mcp 示例配置、经验样例（git 跟踪，139 KB / 21 文件）
//!   - **用户可变状态**：workflows、skills/community、chat-agents、apps、knowledge…
//!     （gitignore，机器相关，有些还是运行时学出来的）
//!
//! 发布版的工作流/技能根走用户数据目录（见 `utils::plugin_root()`），但安装包从来没把
//! 只读资产发出去过（`bundle.resources` 是空的），于是安装版里内置技能一个都看不到。
//!
//! 这里把只读资产在编译期内嵌进二进制，再由 `utils::seed_plugin_assets()` 在启动时
//! 落盘到可写的 plugin 根。相比往 `bundle.resources` 里加条目：
//!   1. 各平台资源目录布局不同（Windows 是 exe 同级，macOS 在 Contents/Resources），
//!      内嵌则与布局无关，不存在"资产落到别处却不报错"的风险；
//!   2. `bundle.resources` 是 map，基础配置与 tauri.windows/linux.conf.json 都定义了它，
//!      合并语义一旦理解错就会把 sherpa DLL 挤掉——那是比本 bug 更严重的回归。
//!
//! **资产清单必须显式allowlist**：绝不能整个 `plugin/` 递归——那会把开发机上门禁的
//! 用户数据（51 MB 的 community 技能、学出来的 ui-maps、用户工作流）烤进发布版二进制。
//! 所以只有 git 跟踪的那些路径进清单，且 mix 目录（ui-maps / experiences）精确到子目录。

use std::path::{Path, PathBuf};

/// 相对仓库根的资产来源。目录递归收集，文件按单个收。
/// 顺序无关（最终按 rel 路径排序输出，保证可复现构建）。
const ASSET_SOURCES: &[&str] = &[
    // 内置技能：整目录都是跟踪内容，递归安全
    "plugin/skills/builtin",
    "plugin/skills/README.md",
    // MCP 配置（默认 servers: {}，用户按需添加 server）
    "plugin/mcp/servers.yaml",
    // ui-maps：只收跟踪的这几个——同目录下 im/media/terminal 是运行时学出来的，绝不内嵌
    "plugin/ui-maps/OpenCode.json",
    "plugin/ui-maps/QQMusic.json",
    "plugin/ui-maps/agent-platform",
    "plugin/ui-maps/desktop",
    // experiences：只收 desktop/——plugin/experiences/workflow 之类是用户攒出来的
    "plugin/experiences/desktop",
];

fn main() {
    // 资产变化必须触发重跑，否则改了内置技能却重建出旧二进制
    for src in ASSET_SOURCES {
        println!("cargo:rerun-if-changed={src}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let repo_root = Path::new(&manifest_dir)
        .parent()
        .expect("src/ 应有父目录（仓库根）")
        .to_path_buf();

    // 整个 plugin/ 缺失是硬错误，不是可容忍的缺失：那意味着这个二进制会"成功构建但
    // 一个内置技能都没有"——静默退化成本次要修的那个缺口本身。宁可构建失败。
    // （真实触发场景：把 lib crate 单独打包/发布，../plugin 不在包内。）
    let plugin_root = repo_root.join("plugin");
    if !plugin_root.is_dir() {
        panic!(
            "plugin/ 目录不存在: {}。随包只读资产（内置技能等）无从内嵌——\
             拒绝构建出没有内置技能的二进制。若在包外构建 lib crate，请带上 plugin/。",
            plugin_root.display()
        );
    }

    let mut assets: Vec<(String, PathBuf)> = Vec::new();
    for src in ASSET_SOURCES {
        let abs = repo_root.join(src);
        if abs.is_dir() {
            collect_dir(&abs, &repo_root, &mut assets);
        } else if abs.is_file() {
            push_asset(&abs, &repo_root, &mut assets);
        } else {
            // 缺失只 warning 不中断：干净 checkout 里资产应当齐全，缺了要能看见
            println!("cargo:warning=plugin 资产缺失，已跳过: {src}");
        }
    }

    // 按 rel 路径排序 → 生成代码与文件系统遍历顺序无关，构建可复现
    assets.sort_by(|a, b| a.0.cmp(&b.0));
    assets.dedup_by(|a, b| a.0 == b.0);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("plugin_assets.rs");

    let mut code = String::with_capacity(assets.len() * 128);
    code.push_str("// @generated by src/build.rs —— 随包只读 plugin 资产表，勿手改。\n");
    code.push_str("// 路径相对 plugin/ 根，供 utils::seed_plugin_assets() 落盘。\n");
    code.push_str("pub static BUNDLED_PLUGIN_ASSETS: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &assets {
        // abs 用绝对路径喂 include_bytes!（内嵌的是内容，路径不会变成运行时字面量）
        code.push_str(&format!(
            "    ({rel:?}, include_bytes!({abs:?})),\n",
            rel = rel,
            abs = abs.to_string_lossy().replace('\\', "/"),
        ));
    }
    code.push_str("];\n");

    std::fs::write(&dest, code).expect("写入 plugin_assets.rs 失败");
    println!(
        "cargo:warning=plugin 只读资产已内嵌: {} 个文件",
        assets.len()
    );
}

/// 递归收集目录下所有文件（按 rel 路径进表）。
fn collect_dir(dir: &Path, repo_root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            println!("cargo:warning=读取资产目录失败 {}: {e}", dir.display());
            return;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_dir(&path, repo_root, out);
        } else if path.is_file() {
            push_asset(&path, repo_root, out);
        }
    }
}

/// 把绝对路径转成「相对 plugin/ 的 rel 键」入表。
fn push_asset(abs: &Path, repo_root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let plugin_root = repo_root.join("plugin");
    let Ok(rel) = abs.strip_prefix(&plugin_root) else {
        println!(
            "cargo:warning=资产不在 plugin/ 下，已跳过: {}",
            abs.display()
        );
        return;
    };
    // 统一用正斜杠：Windows 的 Path::join 认正斜杠，键也保持跨平台一致
    let key = rel.to_string_lossy().replace('\\', "/");
    out.push((key, abs.to_path_buf()));
}
